import path from "path";
import { rollup } from "rollup";

const PATH_ROOT = path.resolve(__dirname, "../");

let inputOptions = {
    input: path.resolve(PATH_ROOT, "index.js"),
    external: ["acorn"]
}

let outputOptions = {
    output: {
        file: path.resolve(PATH_ROOT, "index.cjs.js"),
        format: "cjs",
        banner: "// DO NOT edit this file, it's auto generate from 'constructor/build.js', any changes will be overwrite. \n"
    }
}

rollup(inputOptions).then(bundle => bundle.write(outputOptions));