const path = require("path");
const rollup = require("rollup/dist/rollup.js").rollup;
const commonjs = require("@rollup/plugin-commonjs");

const PATH_ROOT = path.resolve(__dirname, "../");

let inputOptions = {
    input: path.resolve(PATH_ROOT, "index.js"),
    plugins: [commonjs()],
    external: ["acorn"]
}

let outputOptions = {
    output: {
        file: path.resolve(PATH_ROOT, "index.mjs"),
        format: "esm",
        banner: "// DO NOT edit this file, it's auto generate from 'constructor/build.js', any changes will be overwrite. \n"
    }
}

rollup(inputOptions).then(bundle => bundle.write(outputOptions));